CUDA_VISIBLE_DEVICES=0 python scripts/train.py \
--dataset_type ffhq_encode \
--exp_dir experiment/vid_consistency \
--start_from_latent_avg \
--use_w_pool \
--w_discriminator_lambda 0.1 \
--consistency_lambda 0.1 \
--progressive_start 20000 \
--id_lambda 0.5 \
--val_interval 10000 \
--max_steps 200000 \
--stylegan_size 256 \
--stylegan_weights pretrained_models/stylegan2-ffhq-config-f.pt \
--workers 2 \
--batch_size 2 \
--test_batch_size 2 \
--test_workers 2 
